/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cerberus;

public class App {
    StateSpace currentState = StateSpace.Start_State;

    public static void main(String[] args) {
    
    }

    public int sum(int x, int y) {
        return x + y;
    }

    public enum StateSpace{
        Start_State {
          
            public StateSpace toIdleState() {
                return Idle_State;
            }

        },
        Idle_State {
            public StateSpace toWalkState() {
                return Walk_State;
            }
        
            public StateSpace toTurnState() {
                return Turn_State;
            }

            public StateSpace toEndState() {
                return End_State;
            }
        },
        Walk_State {
            public StateSpace toIdleState() {
                return Idle_State;
            }
        },
        Turn_State {
            public StateSpace toIdleState() {
                return Idle_State;
            }
        },
        End_State
        
        // public abstract StateSpace toState();
    }
    public enum EventSpace{
        Transition_Event,
        Sit_ButtonPress_Event,
        Stand_ButtonPress_Event,
        Walk_ButtonPress_Event,
        Turn_ButtonPress_Event,
        End_ButtonPress_Event
    }


    public StateSpace setStartState() {
        return StateSpace.Start_State;
    }

    // public StateSpace addnextState(StateSpace start, StateSpace nextState, EventSpace event) {
    //     // if (start =)
    // }


}
