/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cerberus;

import org.junit.Test;

import cerberus.App.StateSpace;

import static org.junit.Assert.*;

public class AppTest {

    @Test public void sumTest() {
        App classUnderTest = new App();
        assertEquals(3, classUnderTest.sum(1,1));
    }

    @Test public void startTest() {
        App classUnderTest = new App();
        
        assertEquals(StateSpace.Start_State, classUnderTest.currentState);
    }
}
